[build]
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "16"

[[headers]]
for = "/*"
[headers.values]
  Cache-Control = "no-cache"
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'sha256-abcd1234...' 'sha256-efgh5678...' https://www.googletagmanager.com https://plausible.io https://pagead2.googlesyndication.com https://www.tiktok.com 'strict-dynamic';
    script-src-elem 'self' https://www.googletagmanager.com https://plausible.io https://pagead2.googlesyndication.com https://www.tiktok.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
    font-src 'self' https://fonts.gstatic.com;
    img-src 'self' https://uploads.tuntok.live data: https://pagead2.googlesyndication.com https://www.tiktok.com;
    connect-src 'self' https://www.googletagmanager.com https://plausible.io https://region1.google-analytics.com;
    frame-src 'self' https://www.tiktok.com;
    base-uri 'self';
  """