[build]
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "16"

[[headers]]
for = "/*"
[headers.values]
  Cache-Control = "no-cache"
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'nonce-random-nonce-value' https://www.tiktok.com https://www.googletagmanager.com;
    script-src-elem 'self' https://www.tiktok.com https://www.googletagmanager.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    style-src-elem 'self' https://fonts.googleapis.com;
    font-src 'self' https://fonts.gstatic.com;
    img-src 'self' https://uploads.tuntok.live data:;
    connect-src 'self' https://www.googletagmanager.com;
  """