[build]
  publish = "build"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"

[[headers]]
for = "/*"
[headers.values]
  Cache-Control = "no-cache"
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://www.tiktok.com https://*.ttwstatic.com https://www.googletagmanager.com https://plausible.io https://pagead2.googlesyndication.com https://embed.typeform.com https://the.gatekeeperconsent.com https://tally.so;
    script-src-elem 'self' 'unsafe-inline' https://www.tiktok.com https://*.ttwstatic.com https://www.googletagmanager.com https://plausible.io https://pagead2.googlesyndication.com https://embed.typeform.com https://the.gatekeeperconsent.com https://tally.so;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://embed.typeform.com https://sf16-website-login.neutral.ttwstatic.com https://tally.so;
    style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://embed.typeform.com https://sf16-website-login.neutral.ttwstatic.com https://tally.so;
    font-src 'self' https://fonts.gstatic.com;
    img-src 'self' data: https://www.tiktok.com https://*.ttwstatic.com https://uploads.tuntok.live https://pagead2.googlesyndication.com https://embed.typeform.com https://images.typeform.com https://tally.so;
    connect-src 'self' https://www.tiktok.com https://*.ttwstatic.com https://www.googletagmanager.com https://plausible.io https://region1.google-analytics.com https://embed.typeform.com https://api.typeform.com https://tally.so;
    frame-src 'self' https://www.tiktok.com https://embed.typeform.com https://form.typeform.com https://tally.so;
    base-uri 'self';
  """
